[package]
name = "backed_credit_fpc"
type = "contract"
authors = []
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.1", directory = "noir-projects/aztec-nr/aztec" }
token = { path = "../../vendor/aztec-standards/src/token_contract" }
balance_set = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.1", directory = "noir-projects/aztec-nr/balance-set" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.1", directory = "noir-projects/aztec-nr/uint-note" }
fee_juice_contract = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.1", directory = "noir-projects/noir-contracts/contracts/protocol_interface/fee_juice_interface" }
schnorr = { tag = "v0.1.3", git = "https://github.com/noir-lang/schnorr" }
