[workspace]
members = [
    "contracts/fpc",
    "contracts/credit_fpc",
    "contracts/noop",
    "vendor/aztec-standards/src/generic_proxy",
    "vendor/aztec-standards/src/token_contract",
]

[benchmark]
fpc = "profiling/benchmarks/fpc.benchmark.ts"
