[package]
name = "noop"
type = "contract"
authors = []
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.0.0-devnet.2-patch.2", directory = "noir-projects/aztec-nr/aztec" }
